using System.Buffers.Binary;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using AquaControl.Application;
using AquaControl.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using NetTopologySuite.Geometries;
using static AquaControl.Domain.Workflow;
namespace AquaControl.Infrastructure;
public sealed record GeoProgress(string Layer,int Processed,int Accepted,int Rejected,int Omitted,int Warnings,int LayerTotal,string Stage);
public sealed record GeoFieldMapping(string Source,string? Destination);
public sealed record GeoLayerPreview(string Layer,string File,int Records,string Geometry,string? Extent,IReadOnlyList<string> Fields,IReadOnlyList<GeoFieldMapping> Mappings,IReadOnlyList<Dictionary<string,string>> Sample,bool Valid,string? Error);
public sealed record GeoPreview(IReadOnlyList<GeoLayerPreview> Layers,int TotalRecords,bool Valid,int Srid,string Source);
public sealed record GeoSearchItem(string Layer,int Id,string Label,string Detail,double[]? Bounds);
public partial class GeoService(AquaDb db,IConfiguration configuration,IHttpClientFactory clients){
 static readonly GeometryFactory Factory=new(new PrecisionModel(),4326);
 static readonly Dictionary<string,string> Files=new(){["codes"]="Exp_CodigoFijo_4326",["lots"]="Exp_MapaBase_LOTES_4326",["blocks"]="Exp_MapaBase_MZA_4326",["roads"]="Exp_MapaBase_VIAS_4326"};
 static IEnumerable<(Dictionary<string,string> Fields,byte[] Shape)> Read(string stem){
  foreach(var ext in new[]{".shp",".shx",".dbf",".prj"})Require(File.Exists(stem+ext),"Falta archivo "+ext);
  var prj=File.ReadAllText(stem+".prj");Require(prj.Contains("WGS_1984")&&prj.Contains("Degree")&&!prj.Contains("PROJCS"),"Se requiere WGS84 geográfico; no se asigna SRID silenciosamente.");
  var cp=Directory.GetFiles(Path.GetDirectoryName(stem)!).FirstOrDefault(f=>Path.GetFileName(f).Equals(Path.GetFileName(stem)+".cpg",StringComparison.OrdinalIgnoreCase));Require(cp!=null&&File.ReadAllText(cp).Trim().Equals("UTF-8",StringComparison.OrdinalIgnoreCase),"Codificación UTF-8 requerida.");
  var d=File.ReadAllBytes(stem+".dbf");var shx=File.ReadAllBytes(stem+".shx");using var shp=File.OpenRead(stem+".shp");using var reader=new BinaryReader(shp);var header=reader.ReadBytes(100);Require(BinaryPrimitives.ReadInt32BigEndian(header)==9994,"SHP inválido.");Require(BinaryPrimitives.ReadInt32BigEndian(header.AsSpan(24))*2L==shp.Length,"Longitud SHP inválida.");
  int count=BitConverter.ToInt32(d,4),hl=BitConverter.ToUInt16(d,8),rl=BitConverter.ToUInt16(d,10);Require((shx.Length-100)/8==count,"Conteo SHX/DBF no coincide.");var fields=new List<(string Name,int Length)>();for(int p=32;d[p]!=13;p+=32)fields.Add((Encoding.ASCII.GetString(d,p,11).TrimEnd('\0'),d[p+16]));var utf8=new UTF8Encoding(false,true);
  for(int i=0;i<count;i++){var off=shp.Position;var h=reader.ReadBytes(8);Require(h.Length==8,"SHP truncado.");var length=BinaryPrimitives.ReadInt32BigEndian(h.AsSpan(4));Require(BinaryPrimitives.ReadInt32BigEndian(shx.AsSpan(100+i*8))*2L==off&&BinaryPrimitives.ReadInt32BigEndian(shx.AsSpan(104+i*8))==length,"Índice SHX inconsistente.");var shape=reader.ReadBytes(length*2);Require(shape.Length==length*2,"Registro SHP truncado.");int p=hl+i*rl;Require(d[p]!=42,"Registro DBF borrado: revisión requerida.");p++;var row=new Dictionary<string,string>();foreach(var f in fields){row[f.Name]=utf8.GetString(d,p,f.Length).Trim();p+=f.Length;}yield return (row,shape);}
 }
 static Geometry Geometry(byte[] bytes){using var stream=new MemoryStream(bytes);using var r=new BinaryReader(stream);int type=r.ReadInt32();if(type is 1 or 11){var x=r.ReadDouble();var y=r.ReadDouble();var z=type==11?r.ReadDouble():double.NaN;return Factory.CreatePoint(new CoordinateZ(x,y,z));}Require(type is 3 or 5 or 13 or 15,"Geometría no soportada.");stream.Position=36;var parts=r.ReadInt32();var count=r.ReadInt32();var starts=Enumerable.Range(0,parts).Select(_=>r.ReadInt32()).Append(count).ToArray();var coords=new Coordinate[count];for(int i=0;i<count;i++)coords[i]=new CoordinateZ(r.ReadDouble(),r.ReadDouble(),double.NaN);if(type is 13 or 15){r.ReadDouble();r.ReadDouble();for(int i=0;i<count;i++)coords[i].Z=r.ReadDouble();}
  if(type is 3 or 13)return Factory.CreateMultiLineString(Enumerable.Range(0,parts).Select(i=>Factory.CreateLineString(coords[starts[i]..starts[i+1]])).ToArray());
  var rings=Enumerable.Range(0,parts).Select(i=>Factory.CreateLinearRing(coords[starts[i]..starts[i+1]])).ToArray();var polygons=rings.Select(x=>Factory.CreatePolygon(x)).ToArray();var depth=new int[parts];for(int i=0;i<parts;i++)for(int j=0;j<parts;j++)if(i!=j&&polygons[j].Area>polygons[i].Area&&polygons[j].Covers(polygons[i].InteriorPoint))depth[i]++;
  var result=new List<Polygon>();for(int i=0;i<parts;i++)if(depth[i]%2==0){var holes=Enumerable.Range(0,parts).Where(j=>depth[j]==depth[i]+1&&polygons[i].Covers(polygons[j].InteriorPoint)).Select(j=>rings[j]).ToArray();result.Add(Factory.CreatePolygon(rings[i],holes));}return Factory.CreateMultiPolygon(result.ToArray());
 }
 static IReadOnlyList<GeoFieldMapping> Mapping(string layer,IEnumerable<string> fields){var destination=layer switch{"codes"=>new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{"CodF_SQL","CodF_SQL"},{"CodF_SIG","CodF_SIG"},{"CodFijo","CodFijo"},{"Nombre","Nombre"},{"Longi","Longitud"},{"Latid","Latitud"}},"lots"=>new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{"Id","IdOrigen"},{"NroLote","NroLote"}},"blocks"=>new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{"Id","IdOrigen"},{"UV_MZA","UV_MZA"},{"UV","UV"},{"MZA","MZA"}},_=>new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{"OBJECTID","OBJECTID"},{"Nombre","Nombre"},{"name","Nombre"},{"type","TipoVia"},{"OSMID","OSMID"},{"osm_id","OSMID"}}};return fields.OrderBy(x=>x).Select(x=>new GeoFieldMapping(x,destination.GetValueOrDefault(x))).ToList();}
 public Task<GeoPreview> Preview(string folder){
  var result=new List<GeoLayerPreview>();
  foreach(var (layer,file) in Files){try{var rows=Read(Path.Combine(folder,file)).ToList();var fields=rows.SelectMany(x=>x.Fields.Keys).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x).ToList();var types=new HashSet<string>();var envelope=new Envelope();foreach(var row in rows){var geometry=Geometry(row.Shape);types.Add(geometry.GeometryType);envelope.ExpandToInclude(geometry.EnvelopeInternal);}var extent=envelope.IsNull?null:$"{envelope.MinX:F6}, {envelope.MinY:F6}, {envelope.MaxX:F6}, {envelope.MaxY:F6}";result.Add(new GeoLayerPreview(layer,file,rows.Count,string.Join(", ",types),extent,fields,Mapping(layer,fields),rows.Take(20).Select(x=>x.Fields).ToList(),true,null));}catch(Exception ex){result.Add(new GeoLayerPreview(layer,file,0,"",null,[],[],[],false,ex.Message));}}
  return Task.FromResult(new GeoPreview(result,result.Sum(x=>x.Records),result.All(x=>x.Valid),4326,"WGS84 / EPSG:4326"));
 }
 static string? NaturalKey(string layer,Dictionary<string,string> f)=>layer switch{"codes"=>f.GetValueOrDefault("CodFijo")??f.GetValueOrDefault("CodF_SQL")??f.GetValueOrDefault("CodF_SIG"),"lots"=>f.GetValueOrDefault("Id")??f.GetValueOrDefault("NroLote"),"blocks"=>f.GetValueOrDefault("Id")??f.GetValueOrDefault("UV_MZA"),_=>f.GetValueOrDefault("OBJECTID")??f.GetValueOrDefault("OSMID")??f.GetValueOrDefault("osm_id")};
 async Task<HashSet<string>> ExistingKeys(string layer,CancellationToken token){IEnumerable<string?> keys=layer switch{"codes"=>(await db.Set<FixedCode>().AsNoTracking().Select(x=>x.CodFijo!=null?x.CodFijo.ToString():x.CodF_SQL!=null?x.CodF_SQL.ToString():x.CodF_SIG).ToListAsync(token)),"lots"=>(await db.Set<Lot>().AsNoTracking().Select(x=>x.IdOrigen!=null?x.IdOrigen.ToString():x.NroLote).ToListAsync(token)),"blocks"=>(await db.Set<Block>().AsNoTracking().Select(x=>x.IdOrigen!=null?x.IdOrigen.ToString():x.UV_MZA).ToListAsync(token)),_ =>(await db.Set<Road>().AsNoTracking().Select(x=>x.OBJECTID!=null?x.OBJECTID.ToString():x.OSMID).ToListAsync(token))};return keys.Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x!).ToHashSet(StringComparer.OrdinalIgnoreCase);}
 async Task EnsureReplaceAllowed(CancellationToken token){if(await db.Set<Connection>().AnyAsync(token))throw new BusinessException("No se puede reemplazar SIG: existen conexiones asociadas a códigos fijos o vías. Use APPEND o concilie primero los vínculos comerciales.");}
 async Task ClearForReplace(CancellationToken token){await db.Set<GeoIssue>().ExecuteDeleteAsync(token);await db.Set<FixedCode>().ExecuteDeleteAsync(token);await db.Set<Road>().ExecuteDeleteAsync(token);await db.Set<Lot>().ExecuteDeleteAsync(token);await db.Set<Block>().ExecuteDeleteAsync(token);await db.Set<GeoImport>().ExecuteDeleteAsync(token);}
 public async Task Import(string folder,string mode,int? userId,Action<GeoProgress>? progress=null,CancellationToken cancellationToken=default){
  db.Database.SetCommandTimeout(300);
  Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction? replaceTransaction=null;
  try{
  if(mode=="REPLACE"){await EnsureReplaceAllowed(cancellationToken);replaceTransaction=await db.Database.BeginTransactionAsync(cancellationToken);await ClearForReplace(cancellationToken);}
  foreach(var (layer,file) in Files){var stem=Path.Combine(folder,file);var source=Read(stem).ToList();var total=source.Count;using var sha=IncrementalHash.CreateHash(HashAlgorithmName.SHA256);foreach(var ext in new[]{".shp",".shx",".dbf",".prj"})sha.AppendData(File.ReadAllBytes(stem+ext));var hash=Convert.ToHexString(sha.GetHashAndReset());if(await db.Set<GeoImport>().AnyAsync(x=>x.Layer==layer&&x.Hash==hash)){progress?.Invoke(new(layer,total,0,0,total,0,total,"OMITIDA: archivo ya importado"));Console.WriteLine(layer+": ya importado");continue;}
   progress?.Invoke(new(layer,0,0,0,0,0,total,"PREPARANDO"));var tx=replaceTransaction??await db.Database.BeginTransactionAsync(cancellationToken);var ownsTransaction=replaceTransaction==null;var started=DateTime.UtcNow;var import=new GeoImport{Layer=layer,Hash=hash,SourceFile=file+".shp",Mode=mode,Status="IMPORTANDO",UserId=userId,StartedAt=started};db.Add(import);await db.SaveChangesAsync(cancellationToken);int ordinal=0,accepted=0,rejected=0,omitted=0,warnings=0;var existing=mode=="APPEND"?await ExistingKeys(layer,cancellationToken):new HashSet<string>(StringComparer.OrdinalIgnoreCase);
   foreach(var (f,shape) in source){cancellationToken.ThrowIfCancellationRequested();ordinal++;var json=JsonSerializer.Serialize(f);var natural=NaturalKey(layer,f);if(mode=="APPEND"&&(string.IsNullOrWhiteSpace(natural)||!existing.Add(natural))){omitted++;if(string.IsNullOrWhiteSpace(natural)){db.Add(new GeoIssue{ImportId=import.Id,Ordinal=ordinal,Severity="WARNING",Reason="Registro omitido: no tiene clave natural para anexar sin duplicar.",OriginalJson=json});warnings++;}continue;}Geometry g;try{g=Geometry(shape);Require(!g.IsEmpty&&g.IsValid,"Geometría vacía o inválida; no se reparó automáticamente.");Require(g.Coordinates.All(c=>double.IsFinite(c.X)&&double.IsFinite(c.Y)&&Math.Abs(c.X)<=180&&Math.Abs(c.Y)<=90),"Coordenadas fuera de rango.");}catch(Exception ex) when(ex is not OutOfMemoryException){db.Add(new GeoIssue{ImportId=import.Id,Ordinal=ordinal,Severity="ERROR",Reason=ex.Message[..Math.Min(900,ex.Message.Length)],OriginalJson=json});rejected++;continue;}
    string? S(string key)=>f.GetValueOrDefault(key);int? I(string key)=>int.TryParse(S(key),out var v)?v:null;
    if(layer=="codes"){db.Add(new FixedCode{ImportId=import.Id,Ordinal=ordinal,CodF_SQL=I("CodF_SQL"),CodF_SIG=S("CodF_SIG"),CodFijo=I("CodFijo"),Nombre=S("Nombre"),Geom=g,Longitud=g.Coordinate.X,Latitud=g.Coordinate.Y,OriginalJson=json});if(double.TryParse(S("Latid"),CultureInfo.InvariantCulture,out var lat)&&double.TryParse(S("Longi"),CultureInfo.InvariantCulture,out var lon)&&(Math.Abs(lat-g.Coordinate.Y)>0.00001||Math.Abs(lon-g.Coordinate.X)>0.00001)){db.Add(new GeoIssue{ImportId=import.Id,Ordinal=ordinal,Severity="WARNING",Reason="Atributos Longi/Latid difieren del SHP. Consulta usa geometría; atributos preservados.",OriginalJson=json});warnings++;}}
    else if(layer=="lots")db.Add(new Lot{ImportId=import.Id,Ordinal=ordinal,IdOrigen=I("Id"),NroLote=S("NroLote"),Geom=g,OriginalJson=json});
    else if(layer=="blocks")db.Add(new Block{ImportId=import.Id,Ordinal=ordinal,IdOrigen=I("Id"),UV_MZA=S("UV_MZA"),UV=S("UV"),MZA=S("MZA"),Geom=g,OriginalJson=json});
    else db.Add(new Road{ImportId=import.Id,Ordinal=ordinal,OBJECTID=I("OBJECTID"),Nombre=S("Nombre")??S("name"),TipoVia=S("type"),OSMID=S("OSMID")??S("osm_id"),Geom=g,OriginalJson=json});accepted++;
    if(ordinal%300==0){await db.SaveChangesAsync(cancellationToken);db.ChangeTracker.Clear();progress?.Invoke(new(layer,ordinal,accepted,rejected,omitted,warnings,total,"IMPORTANDO"));Console.WriteLine($"{layer}: {ordinal}");}
   }
   cancellationToken.ThrowIfCancellationRequested();await db.SaveChangesAsync(cancellationToken);var tracked=await db.Set<GeoImport>().SingleAsync(x=>x.Id==import.Id,cancellationToken);tracked.Count=accepted;tracked.Rejected=rejected;tracked.Omitted=omitted;tracked.Warnings=warnings;tracked.Status="COMPLETADA";tracked.CompletedAt=DateTime.UtcNow;tracked.DurationMilliseconds=(long)(tracked.CompletedAt.Value-started).TotalMilliseconds;await db.SaveChangesAsync(cancellationToken);if(ownsTransaction){await tx.CommitAsync(cancellationToken);await tx.DisposeAsync();}db.ChangeTracker.Clear();progress?.Invoke(new(layer,ordinal,accepted,rejected,omitted,warnings,total,"COMPLETADA"));Console.WriteLine($"{layer}: {accepted} aceptados, {rejected} rechazados, {omitted} omitidos.");
  }
  progress?.Invoke(new("relaciones",0,0,0,0,0,0,"ASOCIANDO"));
  var blocks=await db.Set<Block>().AsNoTracking().ToListAsync();
  var blockTree=new NetTopologySuite.Index.Strtree.STRtree<Block>();
  foreach(var block in blocks)if(block.Geom!=null)blockTree.Insert(block.Geom.EnvelopeInternal,block);
  var lots=await db.Set<Lot>().ToListAsync();
  foreach(var lot in lots.Where(x=>x.IdManzana==null&&x.Geom!=null)){
   var point=lot.Geom!.InteriorPoint;var matches=blockTree.Query(point.EnvelopeInternal).Where(x=>x.Geom!.Intersects(point)).Take(2).ToList();if(matches.Count==1)lot.IdManzana=matches[0].Id;
  }
  cancellationToken.ThrowIfCancellationRequested();await db.SaveChangesAsync(cancellationToken);db.ChangeTracker.Clear();
  var lotTree=new NetTopologySuite.Index.Strtree.STRtree<Lot>();foreach(var lot in lots)if(lot.Geom!=null)lotTree.Insert(lot.Geom.EnvelopeInternal,lot);
  var codes=await db.Set<FixedCode>().Where(x=>x.IdLote==null).ToListAsync();foreach(var code in codes.Where(x=>x.Geom!=null)){var matches=lotTree.Query(code.Geom!.EnvelopeInternal).Where(x=>x.Geom!.Intersects(code.Geom)).Take(2).ToList();if(matches.Count==1)code.IdLote=matches[0].Id;}
  cancellationToken.ThrowIfCancellationRequested();await db.SaveChangesAsync(cancellationToken);db.ChangeTracker.Clear();
  // Identifiers below come exclusively from this fixed allowlist, never request data.
#pragma warning disable EF1002
  foreach(var table in new[]{"CodigosFijos","Lotes","Manzanas","Vias"})await db.Database.ExecuteSqlRawAsync($"IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='SIX_{table}_Geom' AND object_id=OBJECT_ID('dbo.{table}')) CREATE SPATIAL INDEX SIX_{table}_Geom ON dbo.{table}(Geom) USING GEOMETRY_AUTO_GRID WITH(BOUNDING_BOX=(-61.1,-16.5,-60.8,-16.2));");
#pragma warning restore EF1002
  progress?.Invoke(new("relaciones",0,0,0,0,0,0,"COMPLETADA"));if(replaceTransaction!=null)await replaceTransaction.CommitAsync(cancellationToken);Console.WriteLine("Asociaciones e indices espaciales completados.");
  }catch{if(replaceTransaction!=null)await replaceTransaction.RollbackAsync(CancellationToken.None);throw;}finally{if(replaceTransaction!=null)await replaceTransaction.DisposeAsync();}
 }
 static object Geo(Geometry g){static double[] XY(Coordinate c)=>[c.X,c.Y];static object Rings(Polygon p)=>new[]{p.ExteriorRing.Coordinates.Select(XY).ToArray()}.Concat(Enumerable.Range(0,p.NumInteriorRings).Select(i=>p.GetInteriorRingN(i).Coordinates.Select(XY).ToArray())).ToArray();return g switch { Point p=>new{type="Point",coordinates=(object)XY(p.Coordinate)},LineString l=>new{type="LineString",coordinates=(object)l.Coordinates.Select(XY).ToArray()},Polygon p=>new{type="Polygon",coordinates=Rings(p)},MultiPolygon m=>new{type="MultiPolygon",coordinates=(object)Enumerable.Range(0,m.NumGeometries).Select(i=>Rings((Polygon)m.GetGeometryN(i))).ToArray()},MultiLineString m=>new{type="MultiLineString",coordinates=(object)Enumerable.Range(0,m.NumGeometries).Select(i=>m.GetGeometryN(i).Coordinates.Select(XY).ToArray()).ToArray()},_=>throw new BusinessException("Geometría de salida no soportada.")};}
 static double[]? Bounds(Geometry? g)=>g==null?null:[g.EnvelopeInternal.MinX,g.EnvelopeInternal.MinY,g.EnvelopeInternal.MaxX,g.EnvelopeInternal.MaxY];
 static object Attributes(string json){try{return JsonSerializer.Deserialize<Dictionary<string,string>>(json)??new();}catch{return new Dictionary<string,string>();}}
 public async Task<object> Search(Actor a,string? text,string? selectedLayers,int page,int pageSize){a.Require("geo.read");var term=(text??"").Trim();Require(term.Length>=2,"Escriba al menos dos caracteres para buscar.");Require(page>0&&pageSize is >0 and <=100,"Paginación inválida.");var wanted=(selectedLayers??"codes,lots,blocks,roads").Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).ToHashSet(StringComparer.OrdinalIgnoreCase);Require(wanted.All(x=>Files.ContainsKey(x)),"Capa de búsqueda desconocida.");var numeric=int.TryParse(term,out var number);var rows=new List<GeoSearchItem>();
  if(wanted.Contains("codes"))rows.AddRange((await db.Set<FixedCode>().AsNoTracking().Where(x=>(numeric&&(x.CodFijo==number||x.CodF_SQL==number))||(x.CodF_SIG!=null&&x.CodF_SIG.Contains(term))||(x.Nombre!=null&&x.Nombre.Contains(term))).Take(500).ToListAsync()).Select(x=>new GeoSearchItem("codes",x.Id,x.CodFijo?.ToString()??x.CodF_SIG??$"Código {x.Id}",x.Nombre??"Código fijo",Bounds(x.Geom))));
  if(wanted.Contains("lots"))rows.AddRange((await db.Set<Lot>().AsNoTracking().Where(x=>x.NroLote!=null&&x.NroLote.Contains(term)).Take(500).ToListAsync()).Select(x=>new GeoSearchItem("lots",x.Id,x.NroLote??$"Lote {x.Id}",x.IdManzana==null?"Sin manzana vinculada":$"Manzana {x.IdManzana}",Bounds(x.Geom))));
  if(wanted.Contains("blocks"))rows.AddRange((await db.Set<Block>().AsNoTracking().Where(x=>(x.UV_MZA!=null&&x.UV_MZA.Contains(term))||(x.UV!=null&&x.UV.Contains(term))||(x.MZA!=null&&x.MZA.Contains(term))).Take(500).ToListAsync()).Select(x=>new GeoSearchItem("blocks",x.Id,x.UV_MZA??$"Manzana {x.Id}",$"UV {x.UV??"—"} · MZA {x.MZA??"—"}",Bounds(x.Geom))));
  if(wanted.Contains("roads"))rows.AddRange((await db.Set<Road>().AsNoTracking().Where(x=>(x.Nombre!=null&&x.Nombre.Contains(term))||(x.TipoVia!=null&&x.TipoVia.Contains(term))).Take(500).ToListAsync()).Select(x=>new GeoSearchItem("roads",x.Id,x.Nombre??$"Vía {x.Id}",x.TipoVia??"Vía",Bounds(x.Geom))));
  var ordered=rows.OrderBy(x=>x.Layer).ThenBy(x=>x.Label,StringComparer.OrdinalIgnoreCase).ToList();return new{total=ordered.Count,page,pageSize,items=ordered.Skip((page-1)*pageSize).Take(pageSize)};
 }
 public async Task<object> Detail(Actor a,string layer,int id){a.Require("geo.read");switch(layer){case "codes":{var x=await db.Set<FixedCode>().AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id)??throw new BusinessException("Entidad SIG no encontrada.");return new{type="Feature",id=x.Id,geometry=x.Geom==null?null:Geo(x.Geom),properties=new{layer,label=x.CodFijo?.ToString()??x.CodF_SIG,idLote=x.IdLote,codFijo=x.CodFijo,codFSql=x.CodF_SQL,codFSig=x.CodF_SIG,nombre=x.Nombre,attributes=Attributes(x.OriginalJson)}};}case "lots":{var x=await db.Set<Lot>().AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id)??throw new BusinessException("Entidad SIG no encontrada.");return new{type="Feature",id=x.Id,geometry=x.Geom==null?null:Geo(x.Geom),properties=new{layer,label=x.NroLote,idOrigen=x.IdOrigen,idManzana=x.IdManzana,attributes=Attributes(x.OriginalJson)}};}case "blocks":{var x=await db.Set<Block>().AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id)??throw new BusinessException("Entidad SIG no encontrada.");return new{type="Feature",id=x.Id,geometry=x.Geom==null?null:Geo(x.Geom),properties=new{layer,label=x.UV_MZA,idOrigen=x.IdOrigen,uvMza=x.UV_MZA,uv=x.UV,mza=x.MZA,attributes=Attributes(x.OriginalJson)}};}case "roads":{var x=await db.Set<Road>().AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id)??throw new BusinessException("Entidad SIG no encontrada.");return new{type="Feature",id=x.Id,geometry=x.Geom==null?null:Geo(x.Geom),properties=new{layer,label=x.Nombre,objectId=x.OBJECTID,tipoVia=x.TipoVia,osmId=x.OSMID,attributes=Attributes(x.OriginalJson)}};}default:throw new BusinessException("Capa desconocida.");}}
 public async Task<object> Places(Actor a,double lat,double lon,int radius,CancellationToken token){a.Require("geo.read");Require(double.IsFinite(lat)&&double.IsFinite(lon)&&lat is >=-90 and <=90&&lon is >=-180 and <=180,"Coordenadas inválidas.");Require(radius is >=100 and <=5000,"El radio debe estar entre 100 y 5.000 metros.");var key=configuration["OpenTripMap:ApiKey"];Require(!string.IsNullOrWhiteSpace(key),"OpenTripMap aún no está configurado. Defina AquaControl__OpenTripMap__ApiKey en el servidor.");var apiKey=key!;var language=configuration["OpenTripMap:Language"]??"en";Require(language.Length==2&&language.All(char.IsLetter),"Idioma OpenTripMap inválido.");var url=$"{language}/places/radius?lat={lat.ToString(CultureInfo.InvariantCulture)}&lon={lon.ToString(CultureInfo.InvariantCulture)}&radius={radius}&limit=50&format=geojson&apikey={Uri.EscapeDataString(apiKey)}";using var response=await clients.CreateClient("OpenTripMap").GetAsync(url,token);if(!response.IsSuccessStatusCode)throw new BusinessException("OpenTripMap no pudo consultar los lugares cercanos. Revise la clave y la disponibilidad del proveedor.");using var document=JsonDocument.Parse(await response.Content.ReadAsStreamAsync(token));return document.RootElement.Clone();}
 public async Task<object> Layer(Actor a,string layer,double west,double south,double east,double north){a.Require("geo.read");Require(west>=-180&&east<=180&&south>=-90&&north<=90&&west<east&&south<north,"Extensión inválida.");var box=Factory.ToGeometry(new Envelope(west,east,south,north));var features=new List<object>();const int limit=1000;
  void Add(int id,Geometry? g,object props){if(g!=null)features.Add(new{type="Feature",id,geometry=Geo(g),properties=props});}
  switch(layer){case "codes":foreach(var x in await db.Set<FixedCode>().AsNoTracking().Where(x=>x.Geom!=null&&x.Geom.Intersects(box)).OrderBy(x=>x.Id).Take(limit).ToListAsync())Add(x.Id,x.Geom,new{label=x.CodFijo?.ToString(),x.IdLote});break;
   case "lots":foreach(var x in await db.Set<Lot>().AsNoTracking().Where(x=>x.Geom!=null&&x.Geom.Intersects(box)).OrderBy(x=>x.Id).Take(limit).ToListAsync())Add(x.Id,x.Geom,new{label=x.NroLote,x.IdManzana});break;
   case "blocks":foreach(var x in await db.Set<Block>().AsNoTracking().Where(x=>x.Geom!=null&&x.Geom.Intersects(box)).OrderBy(x=>x.Id).Take(limit).ToListAsync())Add(x.Id,x.Geom,new{label=x.UV_MZA});break;
   case "roads":foreach(var x in await db.Set<Road>().AsNoTracking().Where(x=>x.Geom!=null&&x.Geom.Intersects(box)).OrderBy(x=>x.Id).Take(limit).ToListAsync())Add(x.Id,x.Geom,new{label=x.Nombre});break;
   default:throw new BusinessException("Capa desconocida.");}
  return new{type="FeatureCollection",features,truncated=features.Count==limit};
 }
}
