using AquaControl.Application;
using AquaControl.Domain;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using static AquaControl.Domain.Workflow;
namespace AquaControl.Infrastructure;
public class SecurityService(AquaDb db,AquaService service){
 public static void Password(User u,string password){Require(password.Length>=12&&password.Any(char.IsLetter)&&password.Any(char.IsDigit),"Contraseña de al menos 12 caracteres, letras y números.");u.PasswordSalt=RandomNumberGenerator.GetBytes(32);u.Iterations=600000;u.PasswordHash=Rfc2898DeriveBytes.Pbkdf2(password,u.PasswordSalt,u.Iterations,HashAlgorithmName.SHA256,32);u.SecurityVersion++;}
 public async Task<User?> Login(string login,string password){var normalized=login.Trim().ToLowerInvariant();var user=await db.Set<User>().SingleOrDefaultAsync(x=>x.Login==normalized);if(user==null){Rfc2898DeriveBytes.Pbkdf2(password,new byte[32],600000,HashAlgorithmName.SHA256,32);return null;}if(!user.Active||user.LockedUntil>DateTime.UtcNow)return null;
  var hash=Rfc2898DeriveBytes.Pbkdf2(password,user.PasswordSalt,user.Iterations,HashAlgorithmName.SHA256,32);if(!CryptographicOperations.FixedTimeEquals(hash,user.PasswordHash)){user.FailedAttempts++;if(user.FailedAttempts>=5)user.LockedUntil=DateTime.UtcNow.AddMinutes(15);db.Set<Audit>().Add(new(){UserId=user.Id,Action="sesion.fallida",Resource="login"});await db.SaveChangesAsync();return null;}
  user.FailedAttempts=0;user.LockedUntil=null;if(user.Iterations<600000)Password(user,password);db.Set<Audit>().Add(new(){UserId=user.Id,Action="sesion.iniciar",Resource="login"});await db.SaveChangesAsync();return user;
 }
 public async Task<User> Create(Actor a,string login,string name,string password,int roleId,int? clientId){a.Require("security.manage");using var tx=await db.Database.BeginTransactionAsync();Require(!string.IsNullOrWhiteSpace(login)&&!string.IsNullOrWhiteSpace(name),"Login y nombre requeridos.");await service.Get<Role>(roleId);var u=new User{Login=login.Trim().ToLowerInvariant(),Name=name};Password(u,password);db.Add(u);await db.SaveChangesAsync();db.Add(new UserRole{UserId=u.Id,RoleId=roleId});if(clientId.HasValue){await service.Get<Client>(clientId.Value);db.Add(new UserClient{UserId=u.Id,ClientId=clientId.Value});}service.Audit(a,"usuario.crear",u.Login);await db.SaveChangesAsync();await tx.CommitAsync();return u;}
 public async Task SetRole(Actor a,int id,int roleId,bool active){a.Require("security.manage");Require(id!=a.Id,"No puede cambiar sus propios privilegios desde esta operación.");using var tx=await db.Database.BeginTransactionAsync();var u=await service.Get<User>(id);await service.Get<Role>(roleId);db.RemoveRange(await db.Set<UserRole>().Where(x=>x.UserId==id).ToListAsync());await db.SaveChangesAsync();db.Add(new UserRole{UserId=id,RoleId=roleId});u.Active=active;u.SecurityVersion++;service.Audit(a,"usuario.rol",id.ToString());await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task Reset(Actor a,int id,string password){a.Require("security.manage");var u=await service.Get<User>(id);Password(u,password);u.MustChangePassword=true;u.FailedAttempts=0;u.LockedUntil=null;service.Audit(a,"usuario.restablecer",id.ToString());await db.SaveChangesAsync();}
 public async Task ChangePassword(Actor a,string current,string next){var u=await service.Get<User>(a.Id);var hash=Rfc2898DeriveBytes.Pbkdf2(current,u.PasswordSalt,u.Iterations,HashAlgorithmName.SHA256,32);Require(CryptographicOperations.FixedTimeEquals(hash,u.PasswordHash),"Contraseña actual incorrecta.");Password(u,next);u.MustChangePassword=false;service.Audit(a,"usuario.contrasena",a.Id.ToString());await db.SaveChangesAsync();}
 public static readonly string[] AllPermissions=["portal.read","customers.read","customers.write","readings.write","billing.read","billing.write","billing.adjust","payments.confirm","orders.read","orders.manage","orders.execute","catalogs.write","security.manage","reports.read","geo.read","geo.import"];
 public async Task Seed(string? bootstrapPassword){
  foreach(var p in AllPermissions)if(!await db.Set<Permission>().AnyAsync(x=>x.Code==p))db.Add(new Permission{Code=p});await db.SaveChangesAsync();
  var roles=new Dictionary<string,string[]>{["SUPER ADMIN"]=AllPermissions,["ADMINISTRADOR"]=AllPermissions.Where(p=>p!="security.manage"&&p!="orders.execute").ToArray(),["SUPERVISOR"]=["portal.read","customers.read","billing.read","orders.read","orders.manage","reports.read","geo.read"],["OPERARIO"]=["portal.read","orders.read","orders.execute","geo.read"],["CLIENTE"]=["portal.read"]};
  foreach(var r in roles){var role=await db.Set<Role>().SingleOrDefaultAsync(x=>x.Name==r.Key);if(role==null){role=new Role{Name=r.Key};db.Add(role);await db.SaveChangesAsync();}foreach(var code in r.Value){var pid=await db.Set<Permission>().Where(x=>x.Code==code).Select(x=>x.Id).SingleAsync();if(!await db.Set<RolePermission>().AnyAsync(x=>x.RoleId==role.Id&&x.PermissionId==pid))db.Add(new RolePermission{RoleId=role.Id,PermissionId=pid});}}await db.SaveChangesAsync();
  if(!await db.Set<User>().AnyAsync(x=>x.Login=="aquadmin")){Require(!string.IsNullOrWhiteSpace(bootstrapPassword),"Defina AQUA_BOOTSTRAP_PASSWORD para crear aquadmin.");var u=new User{Login="aquadmin",Name="Administrador AquaControl"};Password(u,bootstrapPassword!);db.Add(u);await db.SaveChangesAsync();db.Add(new UserRole{UserId=u.Id,RoleId=await db.Set<Role>().Where(x=>x.Name=="SUPER ADMIN").Select(x=>x.Id).SingleAsync()});}
  if(!await db.Set<WorkType>().AnyAsync()){foreach(var (code,name,effect) in new[]{("CORTE","Corte por deuda","CORTE"),("INSTALACION","Instalación","NINGUNO"),("MANTENIMIENTO","Mantenimiento","NINGUNO"),("REPARACION","Reparación","NINGUNO"),("RECONEXION","Reconexión","RECONEXION"),("INSPECCION","Inspección","NINGUNO"),("CAMBIO_MEDIDOR","Cambio de medidor","NINGUNO"),("NUEVA_CONEXION","Nueva conexión","NINGUNO"),("FUGA","Atención de fuga","NINGUNO"),("VERIFICACION","Verificación","NINGUNO")}){var t=new WorkType{Code=code,Name=name,Effect=effect};db.Add(t);await db.SaveChangesAsync();db.AddRange(new ActivityTemplate{WorkTypeId=t.Id,Sort=1,Name="Verificar ubicación y conexión"},new ActivityTemplate{WorkTypeId=t.Id,Sort=2,Name="Realizar actividad y registrar resultado",EvidenceRequired=true});}}
  if(!await db.Set<CollectionPolicy>().AnyAsync())db.Add(new CollectionPolicy{Enabled=false});
  if(!await db.Set<Menu>().AnyAsync()){int sort=0;foreach(var d in CatalogService.Definitions)db.Add(new Menu{Name=d.Label,Route=d.Key,Permission=d.Read,Sort=sort++});}
  await db.SaveChangesAsync();
 }
}
