using AquaControl.Domain;
using Microsoft.EntityFrameworkCore;
using System.Data;
using static AquaControl.Domain.Workflow;
namespace AquaControl.Application;
public partial class AquaService {
 public IQueryable<WorkOrder> Orders(Actor a){
  if(a.Can("orders.manage"))return db.Set<WorkOrder>();
  if(a.Can("orders.execute")){var ids=db.Set<Assignment>().Where(x=>x.OperatorId==a.Id&&x.End==null).Select(x=>x.OrderId);return db.Set<WorkOrder>().Where(x=>ids.Contains(x.Id));}
  var contracts=Contracts(a).Select(x=>x.Id);return db.Set<WorkOrder>().Where(x=>x.ContractId!=null&&contracts.Contains(x.ContractId.Value));
 }
 public async Task<WorkOrder> OrderAccess(Actor a,int id)=>await Orders(a).SingleOrDefaultAsync(x=>x.Id==id)??throw new UnauthorizedAccessException("Orden no accesible.");
 async Task Executor(Actor a,WorkOrder o){a.Require("orders.execute");Require(await db.Set<Assignment>().AnyAsync(x=>x.OrderId==o.Id&&x.OperatorId==a.Id&&x.End==null),"Solo el operario asignado puede ejecutar.");}
 public async Task<object> OrderDetail(Actor a,int id){var order=await OrderAccess(a,id);return new{order,activities=await db.Set<OrderActivity>().Where(x=>x.OrderId==id).OrderBy(x=>x.Sort).ToListAsync(),assignments=await db.Set<Assignment>().Where(x=>x.OrderId==id).OrderByDescending(x=>x.Id).ToListAsync(),history=await db.Set<OrderEvent>().Where(x=>x.OrderId==id).OrderByDescending(x=>x.Id).ToListAsync(),evidence=await db.Set<Evidence>().Where(x=>x.OrderId==id).Select(x=>new{x.Id,x.FileName,x.ActivityId,x.CreatedAt}).ToListAsync(),materials=await (from om in db.Set<OrderMaterial>() join m in db.Set<Material>() on om.MaterialId equals m.Id where om.OrderId==id select new{om.Id,m.Name,m.Unit,om.Quantity,om.UnitCost}).ToListAsync()};}
 void Event(Actor a,WorkOrder o,string action,string detail){db.Set<OrderEvent>().Add(new(){OrderId=o.Id,UserId=a.Id,Action=action,Detail=detail});Audit(a,action,"orden:"+o.Id,detail);}
 async Task Notify(WorkOrder o,string message){var recipients=await db.Set<Assignment>().Where(x=>x.OrderId==o.Id&&x.End==null).Select(x=>x.OperatorId).ToListAsync();recipients.Add(o.SupervisorId);foreach(var id in recipients.Distinct())db.Set<Notification>().Add(new(){UserId=id,OrderId=o.Id,Message=message});}
 public async Task<WorkOrder> CreateOrder(Actor a,NewOrder r){
  r=r with {ScheduledAt=r.ScheduledAt.ToUniversalTime()};a.Require("orders.manage");using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var type=await Get<WorkType>(r.WorkTypeId);Require(type.Active,"Tipo inactivo.");Require(r.Priority is "BAJA" or "NORMAL" or "ALTA" or "URGENTE","Prioridad inválida.");Require(!string.IsNullOrWhiteSpace(r.Instructions),"Instrucciones obligatorias.");Require(r.ScheduledAt>=DateTime.UtcNow.Date,"Fecha inválida.");Require((await Permissions(r.SupervisorId)).Contains("orders.manage")&&(await Get<User>(r.SupervisorId)).Active,"Supervisor no autorizado.");
  Connection? c=r.ConnectionId.HasValue?await Get<Connection>(r.ConnectionId.Value):null;
  if(r.ContractId.HasValue){var contract=await Get<Contract>(r.ContractId.Value);Require(contract.ConnectionId==r.ConnectionId,"Contrato y conexión no coinciden.");}
  if(type.Effect is "CORTE" or "RECONEXION")Require(c!=null,"El trabajo requiere conexión.");
  CutNotice? notice=null;if(type.Effect=="CORTE"){
   Require(r.NoticeId.HasValue&&r.ContractId.HasValue,"El corte requiere aviso y contrato.");notice=await Get<CutNotice>(r.NoticeId!.Value);Require(notice.ContractId==r.ContractId&&notice.Status=="VIGENTE"&&notice.OrderId==null,"Aviso no disponible.");Require(r.ScheduledAt>=notice.ScheduledAt,"Respete la fecha de corte del aviso.");Require(await Eligible(notice),"La deuda ya no justifica el corte.");
   Require(!await db.Set<WorkOrder>().AnyAsync(x=>x.ConnectionId==r.ConnectionId&&x.Effect=="CORTE"&&x.Status!="CERRADA"&&x.Status!="CANCELADA"),"Ya existe un corte abierto para esta conexión.");Require(c!.Status!="CORTADA","La conexión ya está cortada.");
  }
  var o=new WorkOrder{Number="OT-"+Guid.NewGuid().ToString("N")[..12].ToUpperInvariant(),WorkTypeId=type.Id,Effect=type.Effect,ContractId=r.ContractId,ConnectionId=r.ConnectionId,SupervisorId=r.SupervisorId,Priority=r.Priority,ScheduledAt=r.ScheduledAt,Longitude=c?.Longitude??r.Longitude,Latitude=c?.Latitude??r.Latitude,Instructions=r.Instructions};Require(Math.Abs(o.Longitude)<=180&&Math.Abs(o.Latitude)<=90,"Coordenadas inválidas.");db.Set<WorkOrder>().Add(o);await db.SaveChangesAsync();
  var templates=await db.Set<ActivityTemplate>().Where(x=>x.WorkTypeId==type.Id).ToListAsync();foreach(var t in templates)db.Set<OrderActivity>().Add(new(){OrderId=o.Id,Name=t.Name,Sort=t.Sort,Required=t.Required,EvidenceRequired=t.EvidenceRequired});if(notice!=null)notice.OrderId=o.Id;Event(a,o,"orden.crear",r.Instructions);await db.SaveChangesAsync();await tx.CommitAsync();return o;
 }
 public async Task Assign(Actor a,int id,AssignOrder r){a.Require("orders.manage");using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);Version(o,r.Version);Require(o.Status is "PENDIENTE" or "ASIGNADA" or "REPROGRAMADA","No se puede reasignar en este estado.");Require((await Get<User>(r.OperatorId)).Active&&(await Permissions(r.OperatorId)).Contains("orders.execute"),"Operario no autorizado.");Require(r.OperatorId!=o.SupervisorId,"Supervisor y ejecutor deben ser distintos.");
  var old=await db.Set<Assignment>().SingleOrDefaultAsync(x=>x.OrderId==id&&x.End==null);if(old!=null){old.End=DateTime.UtcNow;db.Set<Notification>().Add(new(){UserId=old.OperatorId,OrderId=id,Message=$"La orden {o.Number} fue reasignada."});await db.SaveChangesAsync();}
  db.Set<Assignment>().Add(new(){OrderId=id,OperatorId=r.OperatorId,AssignedById=a.Id,Reason=r.Reason});o.Status="ASIGNADA";o.CutAuthorizedAt=null;Event(a,o,"orden.asignar",$"Operario {r.OperatorId}: {r.Reason}");await db.SaveChangesAsync();await Notify(o,$"Orden {o.Number} asignada para {o.ScheduledAt:yyyy-MM-dd}.");await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task Reschedule(Actor a,int id,OrderUpdate r){r=r with {ScheduledAt=r.ScheduledAt.ToUniversalTime()};a.Require("orders.manage");using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);Version(o,r.Version);Check(o.Status,"REPROGRAMADA");Require(r.ScheduledAt>=DateTime.UtcNow.Date&&!string.IsNullOrWhiteSpace(r.Reason),"Fecha y motivo requeridos.");var notice=await db.Set<CutNotice>().FirstOrDefaultAsync(x=>x.OrderId==id&&x.Status=="VIGENTE");Require(notice==null||r.ScheduledAt>=notice.ScheduledAt,"No se puede anticipar el plazo del aviso.");Event(a,o,"orden.reprogramar",$"{o.ScheduledAt:O} → {r.ScheduledAt:O}: {r.Reason}");o.ScheduledAt=r.ScheduledAt;o.Status="REPROGRAMADA";o.CutAuthorizedAt=null;await Notify(o,$"Orden {o.Number} reprogramada.");await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task Transition(Actor a,int id,ChangeOrder r){
  using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);Version(o,r.Version);Check(o.Status,r.Status);
  if(r.Status is "EN_CAMINO" or "FINALIZADA" or "NO_REALIZADA" || (r.Status=="EN_EJECUCION"&&o.Status!="FINALIZADA")) await Executor(a,o);else a.Require("orders.manage");
  if(r.Status=="ASIGNADA")Require(await db.Set<Assignment>().AnyAsync(x=>x.OrderId==id&&x.End==null),"Use Asignar para seleccionar un operario.");
  if(r.Status=="REPROGRAMADA")throw new BusinessException("Use Reprogramar para indicar fecha y motivo.");
  if(r.Status=="VERIFICADA"){Require(o.SupervisorId==a.Id||a.Can("security.manage"),"Debe verificar el supervisor responsable.");Require(!await db.Set<Assignment>().AnyAsync(x=>x.OrderId==id&&x.OperatorId==a.Id),"No puede verificar su propio trabajo.");}
  if(r.Status is "CANCELADA" or "NO_REALIZADA" || o.Status=="FINALIZADA")Require(!string.IsNullOrWhiteSpace(r.Reason),"Motivo obligatorio.");
  if(r.Status=="CANCELADA")Require(o.EffectAt==null,"Ya hubo efecto físico; registre una orden correctiva.");
  if(r.Status=="EN_EJECUCION"){
   if(o.Effect=="CORTE"&&o.EffectAt==null){var n=await db.Set<CutNotice>().SingleOrDefaultAsync(x=>x.OrderId==id&&x.Status=="VIGENTE");Require(n!=null&&await Eligible(n),"Corte no autorizado por deuda vigente.");Require(DateTime.UtcNow>=o.ScheduledAt,"Aún no corresponde ejecutar el corte.");}
   o.StartedAt??=DateTime.UtcNow;
  }
  if(r.Status=="FINALIZADA"){
   Require(!await db.Set<OrderActivity>().AnyAsync(x=>x.OrderId==id&&x.Required&&!x.Done),"Complete las actividades obligatorias.");var required=await db.Set<OrderActivity>().Where(x=>x.OrderId==id&&x.EvidenceRequired).Select(x=>x.Id).ToListAsync();foreach(var aid in required)Require(await db.Set<Evidence>().AnyAsync(x=>x.ActivityId==aid),"Falta evidencia obligatoria.");
   Require(o.Effect is not ("CORTE" or "RECONEXION")||o.EffectAt!=null,"Registre primero el efecto físico sobre el servicio.");o.FinishedAt=DateTime.UtcNow;
  }
  Event(a,o,"orden.estado",$"{o.Status} → {r.Status}: {r.Reason}");o.Status=r.Status;o.Observations=r.Reason;
  if(r.Status=="CANCELADA"){foreach(var ass in await db.Set<Assignment>().Where(x=>x.OrderId==id&&x.End==null).ToListAsync()){db.Set<Notification>().Add(new(){UserId=ass.OperatorId,OrderId=id,Message=$"Orden {o.Number} cancelada: {r.Reason}"});ass.End=DateTime.UtcNow;}}
  await Notify(o,$"Orden {o.Number}: {r.Status}.");await db.SaveChangesAsync();await tx.CommitAsync();
 }
 public async Task Activity(Actor a,int id,int activityId,bool done,string result,string version){using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);await Executor(a,o);Require(o.Status=="EN_EJECUCION","La orden no está en ejecución.");var act=await Get<OrderActivity>(activityId);Require(act.OrderId==id,"Actividad ajena a la orden.");Version(act,version);act.Done=done;act.Result=result;act.DoneAt=DateTime.UtcNow;act.UserId=a.Id;Event(a,o,"actividad.registrar",act.Name);await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task AuthorizeCut(Actor a,int id,string version){using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);await Executor(a,o);Version(o,version);Require(o.Status=="EN_EJECUCION"&&o.Effect=="CORTE"&&o.EffectAt==null,"La orden no admite autorización de corte.");var n=await db.Set<CutNotice>().SingleOrDefaultAsync(x=>x.OrderId==id&&x.Status=="VIGENTE");Require(n!=null&&await Eligible(n)&&DateTime.UtcNow>=o.ScheduledAt,"Corte sin causa o fuera de plazo.");o.CutAuthorizedAt=DateTime.UtcNow;Event(a,o,"corte.autorizar","Autorización online válida 60 segundos; detenerse ante pago o cancelación.");await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task RecordEffect(Actor a,int id,string version){using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);await Executor(a,o);Version(o,version);Require(o.Status=="EN_EJECUCION"&&o.ConnectionId!=null&&o.EffectAt==null,"Efecto no disponible.");var c=await Get<Connection>(o.ConnectionId!.Value);
  if(o.Effect=="CORTE"){var n=await db.Set<CutNotice>().SingleOrDefaultAsync(x=>x.OrderId==id&&x.Status=="VIGENTE");Require(o.CutAuthorizedAt>DateTime.UtcNow.AddSeconds(-60)&&n!=null&&await Eligible(n),"Autorización vencida o deuda pagada: no corte el servicio.");c.Status="CORTADA";}
  else if(o.Effect=="RECONEXION"){Require(c.Status=="CORTADA","Servicio no cortado.");c.Status="ACTIVA";}else throw new BusinessException("Tipo sin efecto físico automatizado.");
  o.EffectAt=DateTime.UtcNow;Event(a,o,"servicio.efecto",c.Status);await db.SaveChangesAsync();await tx.CommitAsync();
 }
 public async Task AddMaterial(Actor a,int id,int materialId,decimal quantity){using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(id);await Executor(a,o);Require(o.Status=="EN_EJECUCION"&&quantity>0,"Estado o cantidad inválidos.");var m=await Get<Material>(materialId);Require(m.Active,"Material inactivo.");db.Set<OrderMaterial>().Add(new(){OrderId=id,MaterialId=materialId,Quantity=quantity,UnitCost=m.Cost,UserId=a.Id});Event(a,o,"material.registrar",m.Name);await db.SaveChangesAsync();await tx.CommitAsync();}
 public async Task AddEvidence(Actor a,Evidence evidence){using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var o=await Get<WorkOrder>(evidence.OrderId);await Executor(a,o);Require(o.Status=="EN_EJECUCION","Orden no está en ejecución.");if(evidence.ActivityId.HasValue)Require((await Get<OrderActivity>(evidence.ActivityId.Value)).OrderId==o.Id,"Actividad ajena.");evidence.UserId=a.Id;db.Set<Evidence>().Add(evidence);Event(a,o,"evidencia.registrar",evidence.FileName);await db.SaveChangesAsync();await tx.CommitAsync();}
 async Task<bool> Eligible(CutNotice n){var policy=await Get<CollectionPolicy>(n.PolicyId);if(!policy.Enabled)return false;var ids=db.Set<NoticeInvoice>().Where(x=>x.NoticeId==n.Id).Select(x=>x.InvoiceId);var invoices=await db.Set<Invoice>().Where(x=>ids.Contains(x.Id)&&x.DueAt<=DateTime.UtcNow.AddDays(-policy.OverdueDays)).ToListAsync();decimal debt=0;foreach(var i in invoices)debt+=await Balance(i.Id);return debt>policy.Threshold;}
 public async Task<CutNotice> CreateNotice(Actor a,int contractId){a.Require("orders.manage");using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable);var c=await Get<Contract>(contractId);Require(c.End==null,"Contrato cerrado.");var policy=await db.Set<CollectionPolicy>().OrderByDescending(x=>x.Id).FirstOrDefaultAsync();Require(policy!=null&&policy.Enabled,"Configure y habilite la política de cobranza.");Require(!await db.Set<CutNotice>().AnyAsync(x=>x.ContractId==contractId&&x.Status=="VIGENTE"),"Ya existe un aviso vigente.");
  var invoices=await db.Set<Invoice>().Where(x=>x.ContractId==contractId&&x.DueAt<=DateTime.UtcNow.AddDays(-policy!.OverdueDays)).ToListAsync();var details=new List<(int Id,decimal Balance)>();foreach(var i in invoices){var balance=await Balance(i.Id);if(balance>0)details.Add((i.Id,balance));}var debt=details.Sum(x=>x.Balance);Require(debt>policy!.Threshold,"No hay deuda que supere el umbral.");
  var n=new CutNotice{ContractId=contractId,PolicyId=policy.Id,ScheduledAt=DateTime.UtcNow.AddDays(policy.NoticeDays),DebtAtIssue=debt};db.Set<CutNotice>().Add(n);await db.SaveChangesAsync();foreach(var d in details)db.Set<NoticeInvoice>().Add(new(){NoticeId=n.Id,InvoiceId=d.Id,Balance=d.Balance});foreach(var u in await db.Set<UserClient>().Where(x=>x.ClientId==c.ClientId).ToListAsync())db.Set<Notification>().Add(new(){UserId=u.UserId,Message=$"Aviso de corte #{n.Id}. Fecha: {n.ScheduledAt:yyyy-MM-dd}. Deuda: {debt:0.00}."});Audit(a,"aviso.crear",n.Id.ToString());await db.SaveChangesAsync();await tx.CommitAsync();return n;
 }
 async Task ReevaluateCuts(int accountId,Actor actor){var contracts=db.Set<Contract>().Where(x=>x.AccountId==accountId).Select(x=>x.Id);var notices=await db.Set<CutNotice>().Where(x=>contracts.Contains(x.ContractId)&&x.Status=="VIGENTE").ToListAsync();foreach(var n in notices){if(await Eligible(n))continue;n.Status="RESUELTO";if(n.OrderId==null)continue;var o=await Get<WorkOrder>(n.OrderId.Value);o.CutAuthorizedAt=null;if(o.EffectAt==null&&o.Status is not ("CANCELADA" or "CERRADA")){o.Status="CANCELADA";Event(actor,o,"corte.cancelado_pago","La deuda dejó de justificar el corte.");await Notify(o,$"PAGO REGISTRADO: no ejecutar corte {o.Number}.");foreach(var assignment in await db.Set<Assignment>().Where(x=>x.OrderId==o.Id&&x.End==null).ToListAsync())assignment.End=DateTime.UtcNow;}else await Notify(o,$"Pago posterior a corte {o.Number}: evaluar reconexión.");}}
}
