using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AquaControl.Domain;

public abstract class Entity { public int Id {get;set;} [Timestamp] public byte[] Version {get;set;}=[]; }
[Table("Usuarios")] public class User:Entity {
 [MaxLength(50)] public string Login {get;set;}=""; [MaxLength(120)] public string Name {get;set;}="";
 public byte[] PasswordHash {get;set;}=[]; public byte[] PasswordSalt {get;set;}=[]; public int Iterations {get;set;}=600000;
 public bool Active {get;set;}=true; public bool MustChangePassword {get;set;} public int FailedAttempts {get;set;} public DateTime? LockedUntil {get;set;} public int SecurityVersion {get;set;}
 public DateTime CreatedAt {get;set;}=DateTime.UtcNow;
}
[Table("Roles")] public class Role:Entity { [MaxLength(50)] public string Name {get;set;}=""; public bool Active {get;set;}=true; }
[Table("UsuariosRoles")] public class UserRole:Entity { public int UserId {get;set;} public int RoleId {get;set;} }
[Table("Permisos")] public class Permission:Entity { [MaxLength(80)] public string Code {get;set;}=""; }
[Table("RolesPermisos")] public class RolePermission:Entity { public int RoleId {get;set;} public int PermissionId {get;set;} }
[Table("UsuarioPermisos")] public class UserPermission:Entity {public int UserId {get;set;} public int PermissionId {get;set;} public bool Allow {get;set;} }
[Table("MenuOpciones")] public class Menu:Entity { public int? ParentId {get;set;} [MaxLength(100)] public string Name {get;set;}=""; [MaxLength(100)] public string Route {get;set;}=""; [MaxLength(80)] public string Permission {get;set;}=""; public int Sort {get;set;} }
[Table("UsuarioMenu")] public class UserMenu:Entity {public int UserId {get;set;} public int MenuId {get;set;} public bool View {get;set;} public bool Create {get;set;} public bool Edit {get;set;} public bool Delete {get;set;} }
[Table("Clientes")] public class Client:Entity { [MaxLength(150)] public string Name {get;set;}=""; [MaxLength(40)] public string Document {get;set;}=""; [MaxLength(100)] public string Email {get;set;}=""; [MaxLength(40)] public string Phone {get;set;}=""; [MaxLength(250)] public string Address {get;set;}=""; public bool Active {get;set;}=true; }
[Table("UsuariosClientes")] public class UserClient:Entity { public int UserId {get;set;} public int ClientId {get;set;} }
[Table("CuentasServicio")] public class Account:Entity { [MaxLength(40)] public string Number {get;set;}=""; public bool Active {get;set;}=true; }
[Table("Sectores")] public class Sector:Entity { [MaxLength(30)] public string Code {get;set;}=""; [MaxLength(100)] public string Name {get;set;}=""; }
[Table("Conexiones")] public class Connection:Entity { [MaxLength(40)] public string Code {get;set;}=""; public int? FixedCodeId {get;set;} public int? SectorId {get;set;} public int? RoadId {get;set;} [MaxLength(250)] public string Address {get;set;}=""; public double Longitude {get;set;} public double Latitude {get;set;} [MaxLength(20)] public string Status {get;set;}="ACTIVA"; }
[Table("ContratosServicio")] public class Contract:Entity {public int AccountId {get;set;} public int ClientId {get;set;} public int ConnectionId {get;set;} public int TariffId {get;set;} public DateTime Start {get;set;}=DateTime.UtcNow; public DateTime? End {get;set;} }
[Table("Medidores")] public class Meter:Entity { [MaxLength(50)] public string Serial {get;set;}=""; [MaxLength(100)] public string Model {get;set;}=""; public bool Active {get;set;}=true; }
[Table("InstalacionesMedidor")] public class MeterInstallation:Entity { public int ConnectionId {get;set;} public int MeterId {get;set;} public DateTime Start {get;set;}=DateTime.UtcNow; public DateTime? End {get;set;} public decimal InitialReading {get;set;} public decimal? FinalReading {get;set;} }
[Table("Lecturas")] public class Reading:Entity { public int InstallationId {get;set;} [MaxLength(7)] public string Period {get;set;}=""; public decimal Value {get;set;} public decimal PreviousValue {get;set;} public DateTime TakenAt {get;set;}=DateTime.UtcNow; public int UserId {get;set;} public bool Estimated {get;set;} [MaxLength(500)] public string Note {get;set;}=""; }
[Table("TarifaVersiones")] public class Tariff:Entity { [MaxLength(100)] public string Name {get;set;}=""; [MaxLength(3)] public string Currency {get;set;}="BOB"; public decimal FixedCharge {get;set;} public decimal UnitPrice {get;set;} public DateTime Start {get;set;}=DateTime.UtcNow; public bool Active {get;set;}=true; }
[Table("TarifaTramos")] public class TariffBand:Entity { public int TariffId {get;set;} public decimal From {get;set;} public decimal? To {get;set;} public decimal Price {get;set;} }
[Table("Facturas")] public class Invoice:Entity { [MaxLength(40)] public string Number {get;set;}=""; public int ContractId {get;set;} public int? ReadingId {get;set;} [MaxLength(7)] public string Period {get;set;}=""; public DateTime IssuedAt {get;set;}=DateTime.UtcNow; public DateTime DueAt {get;set;} public decimal Consumption {get;set;} public decimal Total {get;set;} [MaxLength(3)] public string Currency {get;set;}="BOB"; [MaxLength(150)] public string HolderName {get;set;}=""; [MaxLength(250)] public string HolderAddress {get;set;}=""; }
[Table("FacturaDetalles")] public class InvoiceLine:Entity {public int InvoiceId {get;set;} [MaxLength(150)] public string Description {get;set;}=""; public decimal Quantity {get;set;} public decimal UnitPrice {get;set;} public decimal Amount {get;set;} }
[Table("AjustesFactura")] public class InvoiceAdjustment:Entity {public int InvoiceId {get;set;} public decimal Amount {get;set;} [MaxLength(500)] public string Reason {get;set;}=""; public int UserId {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("IntentosPago")] public class PaymentIntent:Entity {public int AccountId {get;set;} public int UserId {get;set;} [MaxLength(80)] public string Key {get;set;}=""; [MaxLength(12)] public string Method {get;set;}=""; [MaxLength(30)] public string Provider {get;set;}=""; public decimal Amount {get;set;} [MaxLength(3)] public string Currency {get;set;}="BOB"; [MaxLength(20)] public string Status {get;set;}="PENDIENTE"; public string CheckoutUrl {get;set;}=""; public DateTime ExpiresAt {get;set;}=DateTime.UtcNow.AddMinutes(20); }
[Table("Pagos")] public class Payment:Entity {public int AccountId {get;set;} public int IntentId {get;set;} [MaxLength(120)] public string Reference {get;set;}=""; public decimal Amount {get;set;} [MaxLength(12)] public string Method {get;set;}=""; public DateTime ConfirmedAt {get;set;}=DateTime.UtcNow; }
[Table("PagoAplicaciones")] public class PaymentAllocation:Entity { public int PaymentId {get;set;} public int InvoiceId {get;set;} public decimal Amount {get;set;} }
[Table("ReversionesPago")] public class PaymentReversal:Entity {public int PaymentId {get;set;} [MaxLength(120)] public string Reference {get;set;}=""; [MaxLength(500)] public string Reason {get;set;}=""; public int UserId {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("EventosPago")] public class PaymentEvent:Entity { [MaxLength(120)] public string ExternalId {get;set;}=""; public int IntentId {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("TiposTrabajo")] public class WorkType:Entity { [MaxLength(40)] public string Code {get;set;}=""; [MaxLength(100)] public string Name {get;set;}=""; [MaxLength(20)] public string Effect {get;set;}="NINGUNO"; public bool Active {get;set;}=true; }
[Table("ActividadesTrabajo")] public class ActivityTemplate:Entity { public int WorkTypeId {get;set;} public int Sort {get;set;} [MaxLength(200)] public string Name {get;set;}=""; public bool Required {get;set;}=true; public bool EvidenceRequired {get;set;} }
[Table("OrdenesServicio")] public class WorkOrder:Entity { [MaxLength(40)] public string Number {get;set;}=""; public int WorkTypeId {get;set;} [MaxLength(20)] public string Effect {get;set;}="NINGUNO"; public int? ContractId {get;set;} public int? ConnectionId {get;set;} public int SupervisorId {get;set;} [MaxLength(20)] public string Priority {get;set;}="NORMAL"; [MaxLength(20)] public string Status {get;set;}="PENDIENTE"; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime ScheduledAt {get;set;} public DateTime? StartedAt {get;set;} public DateTime? FinishedAt {get;set;} public DateTime? EffectAt {get;set;} public double Latitude {get;set;} public double Longitude {get;set;} [MaxLength(2000)] public string Instructions {get;set;}=""; [MaxLength(2000)] public string Observations {get;set;}=""; public DateTime? CutAuthorizedAt {get;set;} }
[Table("OrdenActividades")] public class OrderActivity:Entity {public int OrderId {get;set;} public int Sort {get;set;} [MaxLength(200)] public string Name {get;set;}=""; public bool Required {get;set;} public bool EvidenceRequired {get;set;} public bool Done {get;set;} [MaxLength(1000)] public string Result {get;set;}=""; public int? UserId {get;set;} public DateTime? DoneAt {get;set;} }
[Table("Asignaciones")] public class Assignment:Entity {public int OrderId {get;set;} public int OperatorId {get;set;} public int AssignedById {get;set;} public DateTime Start {get;set;}=DateTime.UtcNow; public DateTime? End {get;set;} [MaxLength(500)] public string Reason {get;set;}=""; }
[Table("EventosOrden")] public class OrderEvent:Entity {public int OrderId {get;set;} public int UserId {get;set;} [MaxLength(40)] public string Action {get;set;}=""; [MaxLength(2000)] public string Detail {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("Evidencias")] public class Evidence:Entity {public int OrderId {get;set;} public int? ActivityId {get;set;} public int UserId {get;set;} [MaxLength(200)] public string FileName {get;set;}=""; [MaxLength(100)] public string StorageKey {get;set;}=""; [MaxLength(100)] public string ContentType {get;set;}=""; [MaxLength(64)] public string Hash {get;set;}=""; public long Size {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("Materiales")] public class Material:Entity { [MaxLength(40)] public string Code {get;set;}=""; [MaxLength(100)] public string Name {get;set;}=""; [MaxLength(20)] public string Unit {get;set;}="unidad"; public decimal Cost {get;set;} public bool Active {get;set;}=true; }
[Table("OrdenMateriales")] public class OrderMaterial:Entity {public int OrderId {get;set;} public int MaterialId {get;set;} public decimal Quantity {get;set;} public decimal UnitCost {get;set;} public int UserId {get;set;} }
[Table("AvisosCorte")] public class CutNotice:Entity {public int ContractId {get;set;} public int? OrderId {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime ScheduledAt {get;set;} public decimal DebtAtIssue {get;set;} public int PolicyId {get;set;} [MaxLength(20)] public string Status {get;set;}="VIGENTE"; }
[Table("AvisoFacturas")] public class NoticeInvoice:Entity {public int NoticeId {get;set;} public int InvoiceId {get;set;} public decimal Balance {get;set;} }
[Table("PoliticasCobranza")] public class CollectionPolicy:Entity {public decimal Threshold {get;set;} public int OverdueDays {get;set;}=30; public int NoticeDays {get;set;}=7; public bool Enabled {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("Notificaciones")] public class Notification:Entity {public int UserId {get;set;} public int? OrderId {get;set;} [MaxLength(500)] public string Message {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; public DateTime? ReadAt {get;set;} }
[Table("PuntosPago")] public class PaymentPoint:Entity { [MaxLength(100)] public string Name {get;set;}=""; [MaxLength(30)] public string Kind {get;set;}="OFICINA"; [MaxLength(100)] public string Institution {get;set;}=""; [MaxLength(250)] public string Address {get;set;}=""; [MaxLength(150)] public string Hours {get;set;}=""; [MaxLength(50)] public string Methods {get;set;}=""; public double Longitude {get;set;} public double Latitude {get;set;} public bool Active {get;set;}=true; }
[Table("Bitacora")] public class Audit:Entity { public int? UserId {get;set;} [MaxLength(100)] public string Action {get;set;}=""; [MaxLength(100)] public string Resource {get;set;}=""; [MaxLength(2000)] public string Detail {get;set;}=""; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("ImportacionesSIG")] public class GeoImport:Entity { [MaxLength(80)] public string Layer {get;set;}=""; [MaxLength(64)] public string Hash {get;set;}=""; public int Count {get;set;} public int Rejected {get;set;} public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
[Table("IncidenciasSIG")] public class GeoIssue:Entity {public int ImportId {get;set;} public int Ordinal {get;set;} [MaxLength(1000)] public string Reason {get;set;}=""; public string OriginalJson {get;set;}=""; }
