<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../AquaControl.Infrastructure/AquaControl.Infrastructure.csproj"/></ItemGroup><ItemGroup><Content Include="../../Web/**" Link="wwwroot/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
